import React from 'react';
import { X, Shield, FileText, HelpCircle } from 'lucide-react';

interface LegalDocsProps {
  type: 'T&C' | 'POLICY' | 'FAQ' | null;
  onClose: () => void;
}

const LegalDocs: React.FC<LegalDocsProps> = ({ type, onClose }) => {
  if (!type) return null;

  const content = {
    'T&C': {
      title: 'Terms & Conditions',
      icon: <FileText size={24} className="text-primary" />,
      text: (
        <div className="space-y-4 text-gray-300">
          <p><strong>1. Acceptance of Terms:</strong> By using LinguaBridge, you agree to these terms.</p>
          <p><strong>2. User Conduct:</strong> You agree not to use the app for illegal activities. Respect other users.</p>
          <p><strong>3. AI Translation:</strong> Translations are generated by AI (Gemini). We are not responsible for mistranslations.</p>
          <p><strong>4. Account Security:</strong> You are responsible for keeping your login credentials safe.</p>
        </div>
      )
    },
    'POLICY': {
      title: 'Privacy Policy',
      icon: <Shield size={24} className="text-primary" />,
      text: (
        <div className="space-y-4 text-gray-300">
          <p><strong>1. Data Collection:</strong> We collect your name, phone number, and language preference to provide the service.</p>
          <p><strong>2. Audio Data:</strong> Audio is processed for translation in real-time and is not permanently stored by us.</p>
          <p><strong>3. Third Party Services:</strong> We use Google Gemini API for translations. Please refer to Google's Privacy Policy.</p>
        </div>
      )
    },
    'FAQ': {
      title: 'Frequently Asked Questions',
      icon: <HelpCircle size={24} className="text-primary" />,
      text: (
        <div className="space-y-4 text-gray-300">
          <p><strong>Q: Is this app free?</strong><br/>A: Yes, currently the app is in preview mode.</p>
          <p><strong>Q: Which languages are supported?</strong><br/>A: We support English, Hindi, Spanish, French, German, Japanese, Chinese, Russian, and Arabic.</p>
          <p><strong>Q: How accurate is the translation?</strong><br/>A: We use state-of-the-art AI models, but occasional errors may occur.</p>
        </div>
      )
    }
  };

  const activeContent = content[type];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-surface border border-gray-700 w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[80vh]">
        <div className="p-6 border-b border-gray-700 flex items-center justify-between bg-dark/50">
          <div className="flex items-center gap-3">
            {activeContent.icon}
            <h2 className="text-xl font-bold text-white">{activeContent.title}</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
            <X size={24} />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto">
          {activeContent.text}
        </div>

        <div className="p-4 border-t border-gray-700 bg-dark/50 flex justify-end">
          <button 
            onClick={onClose}
            className="px-6 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-white font-medium transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default LegalDocs;
